### ISSUE TITLE
Support OGC mediaType registry to define format references

### ISSUE THREAD

**Issue by fmigneault** [crim-ca/weaver#289]
## Description

Reference to formats media-types provided by OGC registry should be supported: 
http://defs.opengis.net/vocprez/object?uri=http%3A//www.opengis.net/def/media-type

This should allow to resolve CWL namespace/format as follows: 
```yaml 
$namespaces: 
  ogc: http://opengis.net/def/media-type/ogc/1.0
inputs: 
  las-file: 
    type: File
    format: ogc:las
``` 

This would allow referencing specific geospatial types, such as [WKT-CRS](https://www.ogc.org/standards/wkt-crs) and other media-types not defined explicitly in currently supported IANA/EDAM ontologies. 

Investigation must be done in order to figure out how to extract the extension from this registry
(for functions in https://github.com/crim-ca/weaver/blob/master/weaver/formats.py)
