### ISSUE TITLE
[Doubt] process Not found

### ISSUE THREAD

**Issue by pedringcoding** [crim-ca/weaver#309]
Hello,

I try execute the cycle to throw some in CWLTool from swagger and using default configuration in `~/master`.

I see the next steps:

1. I have a weaver app deployed in docker using the `docker-compose.smoke-test.yml` with some changes needed to file performance:

```yml
version: "3.4"

services:
  mongodb:
    image: mongo:3.6.0
    container_name: smoke_test_mongodb
    # mongodb crash with permission denied errors if the command is not overridden like this
    command: bash -c 'chown -R mongodb:mongodb /data && chmod -R 755 /data && mongod --bind_ip_all'
    restart: "no"

  manager:
    image: pavics/weaver:latest-manager
    container_name: smoke_test_manager
    environment:
      FORWARDED_ALLOW_IPS: "*"
    links:
      - mongodb
    ports:
      - "4001:4001"
    volumes:
      - ../../config/weaver.ini:/opt/local/src/weaver/config/weaver.ini
    networks:
      - default
    restart: "no"

  worker:
    image: pavics/weaver:latest-worker
    container_name: smoke_test_worker
    links:
      - mongodb
    volumes:
      - ../../config/weaver.ini:/opt/local/src/weaver/config/weaver.ini
    restart: "no"
```
I run the next command line:
```cmd
docker-compose -f docker-compose.smoke-test.yml up
```

2. I pattern followed to the generate files. See: [Examples](https://github.com/crim-ca/weaver/blob/master/docs/source/examples.rst)

3. I can check if process, HELLOWORD, is registered locally. Efectly, It isn't registered yet. Eg:

Request [GET](http://localhost:4001/processes/HELLOWORLD)
Response: 404
```json
{
  "description": "The resource could not be found. Process with ID 'HELLOWORLD' does not exist.",
  "code": "Not Found",
  "error": {
    "code": 404,
    "status": "404 Not Found"
  }
}
```

4. I'm prepare `DesployProcess_HELLOWORLD.json` to register a basic local process. I using the first example CWL in [commoncwl](https://www.commonwl.org/user_guide/02-1st-example/index.html). Eg:

Request [POST](http://localhost:4001/Processes)
Request body:
```json
{
  "processDescription": {
    "process": {
      "id": "HELLOWORLD",
      "title": "hello world application",
      "abstract": "The test application to display message",
      "visibility": "public"
    }
  },
  "executionUnit": [
    {
      "unit": {
        "cwlVersion": "v1.0",
        "class": "CommandLineTool",
        "baseCommand": "echo",
        "inputs": {
          "message": {
            "type": "string",
            "inputBinding": {
              "position": 1
            }
          }
        },
        "outputs": []
      }
    }
  ],
  "deploymentProfileName": "http://www.opengis.net/profiles/eoc/workflow"
}
```
Response: 201
```json
{
  "processSummary": {
    "keywords": [
      "application"
    ],
    "metadata": [],
    "title": "hello world application",
    "abstract": "The test application to display message",
    "id": "HELLOWORLD",
    "jobControlOptions": [
      "async-execute"
    ],
    "outputTransmission": [],
    "processDescriptionURL": "http://localhost:4001/processes/HELLOWORLD"
  },
  "deploymentDone": true
}
```

5. I can check if process, HELLOWORD, is registered locally. Efectly, It is registered. Eg:

Request [GET](http://localhost:4001/Processes/HELLOWORLD)
Response: 400
```json
{
  "process": {
    "keywords": [
      "application"
    ],
    "metadata": [],
    "title": "hello world application",
    "abstract": "The test application to display message",
    "id": "HELLOWORLD",
    "executeEndpoint": "http://localhost:4001/processes/HELLOWORLD/jobs",
    "inputs": [
      {
        "id": "message",
        "minOccurs": 1,
        "maxOccurs": 1
      }
    ],
    "outputs": [],
    "visibility": "public"
  },
  "jobControlOptions": [
    "async-execute"
  ]
}
```

6. I'm prepare `Execute_HELLOWORLD.json` to execute a process registered locally. Eg:

Request [POST](http://localhost:4001/Processes/HELLOWORLD/execution)
Request body:
```json
{
  "inputs": [
    {
      "id": "message",
      "data": "Hello world!"
    }
  ],
  "outputs": [],
  "mode": "sync",
  "response": "document"
}
```
Response: 404
```json
{
  "description": "The resource could not be found. /processes/HELLOWORLD/execution.",
  "code": "Not Found",
  "error": {
    "code": 404,
    "status": "404 Not Found"
  }
}
```
I can't down weaver level trace at TRACE.
So, Weaver trace at DEBUG level only throw:
```
smoke_test_manager | [2021-08-31 19:09:00,706] WARNING  [MainThread][weaver.tweens] Handled request exception:
smoke_test_manager |   Cause:  [POST http://localhost:4001/processes/HELLOWORLD/execution]
smoke_test_manager |   Raised: [(HTTPNotFound) <404> /processes/HELLOWORLD/execution]
```

What can missing me to complete execution step for this basic example?

- OS: Docker Windows (Hyper-V)
- Browser: Chrome
- Instance: EMS and http://localhost:4001/swagger
- Version: 3.5.0

Thanks for all,
Best regards
