### ISSUE TITLE
Support CWL File contents and OGC-API/WPS raw value as Complex Data input

### ISSUE THREAD

**Issue by fmigneault** [crim-ca/weaver#538]
## Description

Using CWL, it is possible to pass `File` contents directly instead of `path`/`location` using the following definition:
```yaml
input-name:
  class: File
  contents: |
    File contents as literal string
```

Provided that OGC API / WPS Complex Input can be specified by raw `value` instead of `href`, this could be the way to handle the transition with CWL. 

Weaver does not handle well raw data provided as input to a Complex input/output. It expects an `href` at the moment. This doesn't provide the greatest flexibility for users and compliance to OGC specification.

This strategy could be one approach for supporting #51.

## References

- https://www.commonwl.org/v1.2/CommandLineTool.html#File
